#+INCLUDE: ../../+layouts/header.org
#+TITLE: The greatest enemy of learning is knowing.

* Table of Contents                                          :TOC@4:noexport:
- [[#hello-everyone][Hello Everyone]]
- [[#initial-thoughts][Initial thoughts]]
  - [[#why][Why?]]
- [[#thank-you][Thank you]]

* Hello Everyone
A very beautiful quote thanks to the courtesy of *John Maxwell*. Two days ago,
Aasish Sir shared me with a message:

#+begin_quote
For people graduating in 2019 and 2020 if you want to apply in Microsoft for FTE
or intern, send your resume to [[mailto:sanjliagarwal@gmail.com][sanjliagarwal@gmail.com]].
#+end_quote

* Initial thoughts
What an opportunity! And here I’m, not even prepared my *Resume* till now…

** Why?
Um-mm, I had planned to prepare it in Summers just like earlier when [[https://sites.google.com/view/the-launchpad/dev][Dev]] and
[[https://sites.google.com/view/the-launchpad/abhijit][Abhijit]] made their own. Ample of time to think *What goes in and What not*.

* Thank you

#+begin_export html
  <a href="" class="fixedbutton btn btn-social-icon btn-github" onclick="_gaq.push(['_trackEvent', 'btn-social-icon', 'click', 'btn-github']);"><span class="fa fa-github"></span></a>
<script id="dsq-count-scr" src="//imahajanshubham.disqus.com/count.js" async></script>
  <ul class="pager">
      <li class="next">
          <a href="" class="btn btn-neutral float-right" title="" accesskey="n" rel="next">Next <span class="fa fa-arrow-circle-right"></span></a>
      </li>
      <li class="previous">
          <a href="" class="btn btn-neutral" title="" accesskey="n" rel="prev"><span class="fa fa-arrow-circle-left"></span> Previous</a>
      </li>
  </ul>

<div id="disqus_thread"></div>
<script>
var disqus_config = function () {
this.page.url = imahajanshubham.github.io/docs/others/words_to_cherish.html;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = /docs/others/words_to_cherish.html; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://the-greatest-enemy-of-learning-is-knowing.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<script id="dsq-count-scr" src="//the-greatest-enemy-of-learning-is-knowing.disqus.com/count.js" async></script>
#+end_export

#+INCLUDE: ../../+layouts/footer.org
