#+INCLUDE: ../+layouts/header.org
#+TITLE: Home

* Table of Contents                                       :TOC_4_gh:noexport:
- [[#about][About]]
- [[#trending][Trending]]
- [[#latest][Latest]]
- [[#c-c][C-C++]]
  - [[#beware-of-the-assumptions][Beware Of The Assumptions]]
  - [[#occurrence-of-a-digit][Occurrence of a Digit]]
  - [[#acid-naming][Acid Naming]]
  - [[#structures-and-pointers][Structures and Pointers]]
  - [[#only-source-code][Only Source Code]]
    - [[#average-halfify-keteki][Average Halfify (keteki)]]
    - [[#little-chef-and-sums][Little Chef and Sums]]
    - [[#magical-function][Magical Function]]
    - [[#minimizing-the-dot-product][Minimizing the Dot Product]]
- [[#java][Java]]
  - [[#factorials-in-java][Factorials in Java]]
  - [[#hash-maps-in-java][Hash Maps in Java]]
- [[#thank-you][Thank you]]

* About
:PROPERTIES:
  :CUSTOM_ID: about
  :END:
Sharing my views and experience of *Problem Solving* approach via the blog.

* TODO Trending
:PROPERTIES:
  :CUSTOM_ID: trending
  :END:
Coming soon, stay tuned!

* Latest
:PROPERTIES:
  :CUSTOM_ID: latest
  :END:

#+begin_attention
Another interesting blog,\\
Yapp, it’s coming!

*[[https://imahajanshubham.github.io/docs/lang/c-c++/beware_of_the_assumptions.html][Beware Of The Assumptions]]*
#+end_attention

* C-C++
:PROPERTIES:
  :CUSTOM_ID: c-cpp
  :END:
** [[https://imahajanshubham.github.io/docs/lang/c-c++/beware_of_the_assumptions.html][Beware Of The Assumptions]]
:PROPERTIES:
  :CUSTOM_ID: beware-of-the-assumptions
  :END:

#+begin_quote
Calculating the factorials of 100+ using *Divide and Conquer* approach!
#+end_quote

*March 8,* 2018

** [[https://imahajanshubham.github.io/docs/lang/c-c++/occurrences_of_a_digit.html][Occurrence of a Digit]]
:PROPERTIES:
:CUSTOM_ID: occurrence-of-a-digit
:END:

#+begin_quote
The goal was to find the no. of times, *a particular digit appeared* (occurrences) in a *very large positive number*.
#+end_quote

*February 24,* 2018

** [[https://imahajanshubham.github.io/docs/lang/c-c++/acid_naming.html][Acid Naming]]
:PROPERTIES:
:CUSTOM_ID: acid-naming
:END:

#+begin_quote
The goal was to identify the type of acids from the given set of inputs.
#+end_quote

*February 17,* 2018

** [[https://imahajanshubham.github.io/docs/lang/c-c++/structures.html][Structures and Pointers]]
:PROPERTIES:
:CUSTOM_ID: structures-and-pointers
:END:

#+begin_quote
An attempt to share my thoughts on *Structures and Pointer* and finally a small
program using them too.
#+end_quote

*February 7,* 2018

** Only Source Code
:PROPERTIES:
:CUSTOM_ID: only-source-code
:END:
*** [[https://imahajanshubham.github.io/docs/lang/c-c++/only_source_code/average_halfify.html][Average Halfify (keteki)]]
:PROPERTIES:
:CUSTOM_ID: average-halfify
:END:

#+begin_quote
The goal was to calculate the *recursive average of pairs of n numbers*.
#+end_quote

*March 7,* 2018

*** [[https://imahajanshubham.github.io/docs/lang/c-c++/only_source_code/little_chefnsums.html][Little Chef and Sums]]
:PROPERTIES:
:CUSTOM_ID: little-chef-and-sums
:END:

#+begin_quote
The goal was calculate the total of *suffix-sum* and *prefix-sum* of given *n* values
in an array.
#+end_quote

*March 7,* 2018

*** [[https://imahajanshubham.github.io/docs/lang/c-c++/only_source_code/magical_function.html][Magical Function]]
:PROPERTIES:
:CUSTOM_ID: magical-function
:END:

#+begin_quote
The goal was to *recognize the pattern* of a given function.
#+end_quote

*March 7,* 2018

*** [[https://imahajanshubham.github.io/docs/lang/c-c++/only_source_code/minimizing_the_dotproduct.html][Minimizing the Dot Product]]
:PROPERTIES:
:CUSTOM_ID: minimizing-the-dot-product
:END:

#+begin_quote
The goal was to calculate the *minimum dot product of given two vectors*. we could
interchange the vector positions with each other if needed. 
#+end_quote

*March 7,* 2018

* Java
:PROPERTIES:
:CUSTOM_ID: java
:END:
** [[https://imahajanshubham.github.io/docs/lang/java/factorial.html][Factorials in Java]]
:PROPERTIES:
:CUSTOM_ID: factorials-in-java
:END:

#+begin_quote
The goal was to calculate the factorial of say… ~50~, which results in a ~65~
digit answer.
#+end_quote

*February 18,* 2018

** [[https://imahajanshubham.github.io/docs/lang/java/hashmap.html][Hash Maps in Java]]
:PROPERTIES:
:CUSTOM_ID: hash-maps-in-java
:END:

#+begin_quote
a brief introduction about hash maps in java, starting from basic definition,
properties, syntax to creating a simple program of phonebook in java.
#+end_quote

*February 9,* 2018

* Thank you
:PROPERTIES:
:CUSTOM_ID: thank-you
:END:

#+begin_export html
  <a href="https://github.com/imahajanshubham/docs/blob/master/%2Bposts/home.org" class="fixedbutton btn btn-social-icon btn-github" onclick="_gaq.push(['_trackEvent', 'btn-social-icon', 'click', 'btn-github']);"><span class="fa fa-github"></span></a>

  <ul class="pager">
      <li class="next">
          <a href="https://imahajanshubham.github.io/docs/lang/c-c++/structures.html" class="btn btn-neutral float-right" title="Structures And Pointers" accesskey="n" rel="next">Next <span class="fa fa-arrow-circle-right"></span></a>
      </li>
      <li class="previous">
          <a href="https://imahajanshubham.github.io/docs/lang/c-c++/beware_of_the_assumptions.html" class="btn btn-neutral" title="Beware Of The Assumptions" accesskey="n" rel="prev"><span class="fa fa-arrow-circle-left"></span> Previous</a>
      </li>
  </ul>


<div id="disqus_thread"></div>
<script>
var disqus_config = function () {
this.page.url = imahajanshubham.github.io/docs/home.html;  // Replace PAGE_URL with your page's canonical URL variable
this.page.identifier = /docs/home.html; // Replace PAGE_IDENTIFIER with your page's unique identifier variable
};
(function() { // DON'T EDIT BELOW THIS LINE
var d = document, s = d.createElement('script');
s.src = 'https://the-greatest-enemy-of-learning-is-knowing.disqus.com/embed.js';
s.setAttribute('data-timestamp', +new Date());
(d.head || d.body).appendChild(s);
})();
</script>
<noscript>Please enable JavaScript to view the <a href="https://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
<script id="dsq-count-scr" src="//the-greatest-enemy-of-learning-is-knowing.disqus.com/count.js" async></script>
#+end_export

#+INCLUDE: ../+layouts/footer.org
